Messages:
  Errors:
    e_null_args: "Ошибка: мало аргументов"
    e_no_sign: "Ошибка: блок не является табличкой"
    e_null_world_name: "Ошибка: пустое имя мира"
    e_world_exist: "Ошибка: такой мир уже существует"
    e_cant_d_world: "Ошибка: невозможно удалить выбранный мир"
    e_world_nf: "Ошибка:мир не найден"
    e_invalid_command: "Ошибка: неверная команда"
    e_too_more_args: "Ошибка: лишние аргументы"
    e_game_world: "Ошибка: нельзя удалить основной мир игры"
    e_invalid_prefix: "Ошибка: имя мира должно начинаться с (_) пример: _test"
    e_world_d_error: "Ошибка: невозможно удалить выбранный мир"
    e_no_permission: "Ошибка: недостаточно прав"
    e_no_args: "Ошибка: мало аргументов"
    e_already_gaming: "Ошибка: Вы уже играете"
    e_already_voted: ...вы уже проголосовали упсссс))..."
    e_arena_nf: "...нет такой арены упсссс))..."
    e_nan: "Ошибка: введите числовые значения"
    e_sign_select: "Ошибка: наведите курсор на табличку"
    e_arena_type_incorrect: "Ошибка: неверный тип арены"
    e_arena_respawn_not_exists: "Ошибка: такой точки респавна не существует"
    e_arena_respawn_point_exists: "Ошибка: такая точка уже есть"
    e_arena_respawn_point_nf: "Ошибка: такой точки нет"
  Chat:
    c_clear_line: "\n"
    c_bar: "§a\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8\u25C8"
  Success:
    s_voted: "...ваш голос учтен..."
    s_world_created: "Мир создан"
    s_world_saved_closed: "Мир сохранен"
    s_teleported_to_world: "Телепортирование в мир"
    s_world_deleted: "Мир удален"
    s_sign_set: "Знак установлен"
  Arena:
    e_not_play: "§7[§c*§7] §e %1$s §cубил §e%2$d"
    e_not_play: "§7[§c*§7] §eвы не на арене!"
    e_arena_rebuild: "§7[§c*§7] §eдождитесь когда арена перезапустится"
    e_arena_disabled: "§7[§c*§7] §eарена отключена."
    a_arena_started: "§7[§c*§7] §eигра началась"
    a_arena_bs_start_timer: "§7[§c*§7] §eготовность §b%1$d §eсек.!"
    a_arena_start_timer: "§7[§c*§7] §eдо начала игры §b%1$d §eсек."
    a_players_not_enought: "§7[§c*§7] §eстарт откладывается, требуется §b%1$d §eигроков, на арене - §b%2$d"
    a_player_join_to_player: "§7[§c*§7]§e вы зашли на арену (§b%2$d§e\\§b%3$d§e) §eдля выхода введите §c/arena leave §eили нажмите на §cтабличку§e или §cкровать"
    a_player_spectate_to_others: "§7[§c*§7] %1$s §eнаблюдает"
    a_player_spectate_stop_to_others: "§7[§c*§7] %1$s §eперестал наблюдать"
    a_player_spectate_to_player: "§7[§c*§7]§e вы зашли как наблюдатель"
    a_player_join_to_others: "§7[§c*§7] %1$s §eзашел на арену (§b%2$d§e\\§b%3$d§e)"
    a_player_lose_to_others: "§7[§c*§7]§e %1$s §cумер! §e%2$d §cигроков осталось"
    a_player_lose_to_player: "§7[§c*§7]§e теперь вы наблюдатель"
    a_player_leave_to_others: "§7[§c*§7] %1$s §eпокинул арену (§b%2$d§e\\§b%3$d§e)"
    a_player_win_to_all: "            §7 %1$s §eвыйграл на арене§b %2$s"
    a_player_no_winners: "            §eвыживших не осталось..."
  Lobby:
    l_arena_status_disabled: "\u00A77[\u00A7cTNTRun\u00A77]\u00A7e арена временно отключена"
    l_player_voted_to_player: "[TNTRun] вы проголосовали за арену %1$s"
    l_player_voted_to_other: "[TNTRun] %1$s - проголосовало %2$d/%3$d"
    l_vote_message_to_all: ""